### ISSUE TITLE
Creation exercices

### ISSUE THREAD

**Issue by LongPointyEyes** [HE-Arc/EZWorkout#40]
La création de nouveau exercices pour un entrainement donné (pas l'ajout) ne marche pas ou pas toujours

**Comment by jojoc4** [comment]
Je n'arrive pas à reproduire le bug.

**Comment by jojoc4** [comment]
Il n'a pas été possible de reproduire le bug que ce soit sur la version en production ou sur la branche dev. Il est donc considéré résolu.
